# 插件在哪些世界禁用，世界名区分大小写
disable-worlds:
  - disableWorld1
  - disableWorld2

# 铁门方块材质
door-blocks:
  - IRON_DOOR
  - IRON_DOOR_BLOCK

create:
  # 在第一行匹配时，创建收费门
  sign-line: '$lock'
  # 创建收费门需要多少金币
  create-price: 0
  # 默认价格
  default-price: 0
  # 默认传送到门外多远的距离
  default-reach-enter: 0
  default-reach-leave: 0

# 收费铁门牌子内容，支持 MiniMessage
lock-sign:
  - '<dark_aqua>[<aqua><b>收费门</b><dark_aqua>]'
  - '%price% 金币'
  - '<u>%player%'
  - '%flags%'

money:
  # 最小和最大价格限制，设为 unlimited 则不限制
  min: 0.0
  max: 10000.0
  # 价格显示格式
  format: '%.1f'
  # 如果价格是整数，去除小数部分
  # 注释该选项关闭这个功能
  replace-empty: '.0'
  # 玩家进入收费门时，向创建者收取百分之多少的税收
  tax: '0%'

reach:
  # 最小和最大的传送距离限制
  enter:
    min: 0
    max: 0
  leave:
    min: 0
    max: 0

prevent-solid-target:
  # 如果目标传送位置是实心方块，不进行传送
  enable: true
  # 碰撞箱高度大于等于多少的方块，属于实心方块
  # 碰撞箱接口从 1.13 开始提供，低于此版本，该选项无效
  min-height: 0.6
  # 其它不属于实心方块的方块
  # 但能被活塞推动后被破坏的，恒不属于实心方块
  # 如果玩家无法传送到收费门对面，请添加方块到这里
  not-solid-materials:
    - STEP
    - WOOD_STEP
    - FENCE_GATE
    - HOPPER
    - SLIME
    - SLIME_BLOCK
    - WATER
    - STATIONARY_WATER
    - LAVA
    - STATIONARY_LAVA

# 标志显示内容
flags:
  # 显示顺序
  order:
    - can-enter
    - can-leave
    - no-items
    - no-money
    - no-potions
  # 显示内容
  display:
    can-enter:
      with: '进'
      none: ''
      info: '允许进入'
    can-leave:
      with: '出'
      none: ''
      info: '允许离开'
    no-items:
      with: '空'
      none: ''
      info: '要求进入时背包为空'
    no-money:
      with: '钱'
      none: ''
      info: '要求进入时没有金币 (或刚好可支付进入)'
    no-potions:
      with: '效'
      none: ''
      info: '要求进入时没有药水效果'
