# 插件在哪些世界禁用，世界名区分大小写
disable-worlds:
  - disableWorld1
  - disableWorld2

# 铁门方块材质
door-blocks:
  - IRON_DOOR
  - IRON_DOOR_BLOCK

# 扩展功能: 容器内容预览
view-container:
  # 要求告示牌包含什么内容时，点击告示牌预览容器
  # 取消注释这个选项，则启用此功能
  #sign: '查看容器'
  # 哪些容器可以触发预览
  # https://javadoc.mcio.dev/spigot/1.21.4/org/bukkit/event/inventory/InventoryType.html
  # 默认有 箱子、发射器、投掷器、漏斗、潜影箱、木桶
  types:
    - CHEST
    - DISPENSER
    - DROPPER
    - HOPPER
    - SHULKER_BOX
    - BARREL
  # 什么操作点击告示牌，可以触发预览
  # LEFT, RIGHT, SHIFT_LEFT, SHIFT_RIGHT
  actions:
    - SHIFT_LEFT

create:
  # 在第一行匹配时，创建收费门
  sign-line: '$lock'
  # 创建收费门需要多少金币
  create-price: 0
  # 默认价格
  default-price: 0
  # 默认传送到门外多远的距离
  default-reach-enter: 0
  default-reach-leave: 0

# 权限组配置
# 组名不能为 default，不能包含英文的点符号 (.)
# 玩家拥有权限 sweet.locks.group.<组名> 即代表玩家在某个组内
# priority 越小的组越先匹配
groups:
  # 示例组名，其对应的权限是 sweet.locks.group.vip
  vip:
    # 优先级
    priority: 1000
    # 以下选项均为可选，如果删除某项，则该项使用配置文件中的默认值
    create-price: 0
    money:
      min: 0.0
      max: 10000.0
      tax: '0%'
    reach-enter:
      min: 0
      max: 0
    reach-leave:
      min: 0
      max: 0

# 收费铁门牌子内容，支持 MiniMessage
lock-sign:
  - '<dark_aqua>[<aqua><b>收费门</b><dark_aqua>]'
  - '%price% 金币'
  - '<u>%player%'
  - '%flags%'

money:
  # 最小和最大价格限制，设为 unlimited 则不限制
  min: 0.0
  max: 10000.0
  # 价格显示格式
  format: '%.1f'
  # 如果价格是整数，去除小数部分
  # 注释该选项关闭这个功能
  replace-empty: '.0'
  # 玩家进入收费门时，向创建者收取百分之多少的税收
  tax: '0%'

reach:
  # 最远支持在多少格以内进出收费门，设为 -1 则禁用这个限制
  interact: 2.6
  # 最小和最大的传送距离限制
  enter:
    min: 0
    max: 0
  leave:
    min: 0
    max: 0

prevent-solid-target:
  # 如果目标传送位置是实心方块，不进行传送
  enable: true
  # 碰撞箱高度大于等于多少的方块，属于实心方块
  # 碰撞箱接口从 1.13 开始提供，低于此版本，该选项无效
  min-height: 0.6
  # 其它不属于实心方块的方块
  # 但能被活塞推动后被破坏的，恒不属于实心方块 (活塞推动判定不完全，有些方块没有判定到位)
  # 如果玩家无法传送到收费门对面，请添加方块到这里
  not-solid-materials:
    - STEP
    - WOOD_STEP
    - FENCE_GATE
    - HOPPER
    - SLIME
    - SLIME_BLOCK
    - WATER
    - STATIONARY_WATER
    - LAVA
    - STATIONARY_LAVA
    - WOODEN_PLATE
    - STONE_PLATE
    - IRON_PLATE
    - GOLD_PLATE

# 标志显示内容
flags:
  # 显示顺序
  order:
    - can-enter
    - can-leave
    - no-items
    - no-money
    - no-potions
  # 显示内容
  display:
    can-enter:
      with: '进'
      none: ''
      info: '允许进入'
    can-leave:
      with: '出'
      none: ''
      info: '允许离开'
    no-items:
      with: '空'
      none: ''
      info: '要求进入时背包为空'
    no-money:
      with: '钱'
      none: ''
      info: '要求进入时没有金币 (或刚好可支付进入)'
    no-potions:
      with: '效'
      none: ''
      info: '要求进入时没有药水效果'
