name: SweetLocks
version: '${version}'
main: top.mrxiaom.sweet.locks.SweetLocks
api-version: 1.13
softdepend:
  - Vault
  - PlaceholderAPI
folia-supported: true
authors: [ MrXiaoM ]
libraries:
  - "org.jetbrains:annotations:24.0.0"
commands:
  sweetlocks:
    description: 'The main command of SweetLocks'
    aliases: [ slocks, locks, sl ]
